#!/usr/bin/env node

/**
 * Test script to convert a fixture and write output for debugging
 *
 * Usage: node scripts/test-convert.js <fixture-path>
 * Example: node scripts/test-convert.js fixtures/ui-core/CircularButton.tsx
 */

const fs = require('fs')
const path = require('path')
const { analyzeComponent } = require('../dist/tools/analyzeComponent.js')
const { convertStyles } = require('../dist/tools/convertStyles.js')
const { suggestMigration } = require('../dist/tools/suggestMigration.js')

const inputPath = process.argv[2]

if (!inputPath) {
  console.error('Usage: node scripts/test-convert.js <fixture-path>')
  console.error('Example: node scripts/test-convert.js fixtures/ui-core/CircularButton.tsx')
  process.exit(1)
}

const fileName = path.basename(inputPath, '.tsx')
const outputDir = path.join(__dirname, '../fixtures/output')

// Ensure output dir exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true })
}

console.log(`\n📁 Input: ${inputPath}`)
console.log(`📂 Output: fixtures/output/${fileName}.*\n`)

// 1. Analyze
console.log('🔍 Analyzing...')
const analysis = analyzeComponent({ filePath: inputPath })
fs.writeFileSync(
  path.join(outputDir, `${fileName}.analysis.json`),
  JSON.stringify(analysis, null, 2)
)
console.log(`   Summary: ${analysis.summary.totalPatterns} patterns found`)
console.log(`   - Auto-convertible: ${analysis.summary.autoConvertible}`)
console.log(`   - AI-assisted: ${analysis.summary.aiAssisted}`)
console.log(`   - Manual: ${analysis.summary.manualRequired}`)

// 2. Convert
console.log('\n🔄 Converting...')
const conversion = convertStyles({ filePath: inputPath })
fs.writeFileSync(
  path.join(outputDir, `${fileName}.conversion.json`),
  JSON.stringify(conversion, null, 2)
)
console.log(`   Conversions: ${conversion.conversions.length}`)
console.log(`   Skipped: ${conversion.skipped.length}`)

// 3. Write readable output
const originalSource = fs.readFileSync(inputPath, 'utf-8')
let output = `// Original: ${inputPath}\n`
output += `// Generated by: node scripts/test-convert.js\n\n`
output += `/* ========== ANALYSIS ==========\n`
output += `Total patterns: ${analysis.summary.totalPatterns}\n`
output += `Auto-convertible: ${analysis.summary.autoConvertible}\n`
output += `AI-assisted: ${analysis.summary.aiAssisted}\n`
output += `Manual required: ${analysis.summary.manualRequired}\n`
output += `Tokens found: ${analysis.tokens.join(', ') || 'none'}\n`
output += `================================ */\n\n`

output += `/* ========== CONVERSIONS ========== */\n\n`
for (const conv of conversion.conversions) {
  output += `// Line ${conv.lineNumber} (${conv.type}, confidence: ${conv.confidence})\n`
  output += `// BEFORE:\n`
  output += conv.original.split('\n').map(l => `//   ${l}`).join('\n') + '\n'
  output += `// AFTER:\n`
  output += conv.converted.split('\n').map(l => `//   ${l}`).join('\n') + '\n\n'
}

if (conversion.skipped.length > 0) {
  output += `/* ========== SKIPPED (needs manual) ========== */\n\n`
  for (const skip of conversion.skipped) {
    output += `// Line ${skip.lineNumber}: ${skip.reason}\n`
    output += `// Suggested: ${skip.suggestedApproach}\n`
    output += skip.code.split('\n').map(l => `//   ${l}`).join('\n') + '\n\n'
  }
}

fs.writeFileSync(path.join(outputDir, `${fileName}.output.txt`), output)

console.log(`\n✅ Output files:`)
console.log(`   fixtures/output/${fileName}.analysis.json`)
console.log(`   fixtures/output/${fileName}.conversion.json`)
console.log(`   fixtures/output/${fileName}.output.txt`)
